Devops 81
viasoftkorp/KorpSetupLinux pull request #160
Opened 2022-11-03 18:32 UTC by gustavokorp

2022-11-07 11:48 UTC, Radins requested changes

2022-11-07 11:48 UTC, Radins commented on roles/utils/tasks/consul_kv/ensure_kv.yml
> +
remover espaços desnecessários

2022-11-07 11:48 UTC, Radins commented on roles/utils/tasks/services/vars_validation.yml
> +- name: "Definição de service_vars com sufixo para {{ service_name }}"
"Definição de sufixo do nome do banco de dados"

2022-11-07 11:48 UTC, Radins commented on setup.sh
> +    db_sufix = ""
Isso não foi testado, esse 'if' seria para pegar a prop do arquivo setup_config.ini

2022-11-07 11:48 UTC, Radins commented on setup.sh
> +   db_sufix=$db_sufix
a princípio esse 'else' é desnecessário.

2022-11-17 13:27 UTC, Radins requested changes

2022-11-17 13:27 UTC, Radins commented on roles/utils/tasks/default/variables_setup.yml
> +          when: not (customs.db_sufix | length == 0) and authentication_db_name == "Viasoft_Authentication"
não utiliza `customs.db_sufix`, somente `db_sufix`

2022-11-17 13:27 UTC, Radins commented on roles/utils/tasks/default/variables_setup.yml
> +          when: not (customs.db_sufix | length == 0) and authentication_db_name == "Viasoft_Authentication"
por que desse `and`?

2022-11-17 13:27 UTC, Radins commented on roles/utils/tasks/default/variables_setup.yml
> +
remover essas linhas vazias

2022-11-17 13:27 UTC, Radins commented on roles/utils/tasks/services/vars_validation.yml
> +  when: service_vars.db is defined and db_sufix is defined and db_sufix != ""
db_sufix sempre vai estar definido, ele está sendo definido em group_vars/all

2022-11-17 13:27 UTC, Radins commented on setup.sh
> +    echo "$install_apps"
remove esse `echo`

2022-11-17 13:27 UTC, Radins commented on setup.sh
> +    echo "$status_code"
remove esse echo

2022-11-17 13:27 UTC, Radins commented on setup.sh
> +  }' -C DEVOPS-81
remover `-C`

2022-11-17 17:08 UTC, Radins approved these changes

2022-11-18 11:54 UTC, kewinbrand requested changes
adicionar a propriedade DatabaseTableName ao KV do Korp.Legacy.Authentication

2022-11-18 13:20 UTC, kewinbrand approved these changes

2022-11-18 13:27 UTC, merged